[package]
name = "transmogrify"
version = "0.0.1"
authors = [ "rob thijssen <rthijssen@gmail.com>" ]

[dependencies]
chrono = { version = "^0.4", features = ["serde"] }
lazy_static = "^1.3"
regex = "^1.1"
reqwest = "^0.9"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
yaml-rust = "^0.4"